// <auto-generated>Generated from the .NET 10 System.Drawing.Primitives tables.</auto-generated>
#nullable enable

namespace System.Drawing;
internal static class KnownColorTable
{
    /// <summary>ARGB values indexed by <see cref="KnownColor"/>; system colors use Windows defaults.</summary>
    public static readonly uint[] Argb =
    [
        0x00000000, // (unused)
        0xFFB4B4B4, // ActiveBorder
        0xFF99B4D1, // ActiveCaption
        0xFF000000, // ActiveCaptionText
        0xFFABABAB, // AppWorkspace
        0xFFF0F0F0, // Control
        0xFFA0A0A0, // ControlDark
        0xFF696969, // ControlDarkDark
        0xFFE3E3E3, // ControlLight
        0xFFFFFFFF, // ControlLightLight
        0xFF000000, // ControlText
        0xFF000000, // Desktop
        0xFF6D6D6D, // GrayText
        0xFF0078D7, // Highlight
        0xFFFFFFFF, // HighlightText
        0xFF0066CC, // HotTrack
        0xFFF4F7FC, // InactiveBorder
        0xFFBFCDDB, // InactiveCaption
        0xFF000000, // InactiveCaptionText
        0xFFFFFFE1, // Info
        0xFF000000, // InfoText
        0xFFF0F0F0, // Menu
        0xFF000000, // MenuText
        0xFFC8C8C8, // ScrollBar
        0xFFFFFFFF, // Window
        0xFF646464, // WindowFrame
        0xFF000000, // WindowText
        0x00FFFFFF, // Transparent
        0xFFF0F8FF, // AliceBlue
        0xFFFAEBD7, // AntiqueWhite
        0xFF00FFFF, // Aqua
        0xFF7FFFD4, // Aquamarine
        0xFFF0FFFF, // Azure
        0xFFF5F5DC, // Beige
        0xFFFFE4C4, // Bisque
        0xFF000000, // Black
        0xFFFFEBCD, // BlanchedAlmond
        0xFF0000FF, // Blue
        0xFF8A2BE2, // BlueViolet
        0xFFA52A2A, // Brown
        0xFFDEB887, // BurlyWood
        0xFF5F9EA0, // CadetBlue
        0xFF7FFF00, // Chartreuse
        0xFFD2691E, // Chocolate
        0xFFFF7F50, // Coral
        0xFF6495ED, // CornflowerBlue
        0xFFFFF8DC, // Cornsilk
        0xFFDC143C, // Crimson
        0xFF00FFFF, // Cyan
        0xFF00008B, // DarkBlue
        0xFF008B8B, // DarkCyan
        0xFFB8860B, // DarkGoldenrod
        0xFFA9A9A9, // DarkGray
        0xFF006400, // DarkGreen
        0xFFBDB76B, // DarkKhaki
        0xFF8B008B, // DarkMagenta
        0xFF556B2F, // DarkOliveGreen
        0xFFFF8C00, // DarkOrange
        0xFF9932CC, // DarkOrchid
        0xFF8B0000, // DarkRed
        0xFFE9967A, // DarkSalmon
        0xFF8FBC8F, // DarkSeaGreen
        0xFF483D8B, // DarkSlateBlue
        0xFF2F4F4F, // DarkSlateGray
        0xFF00CED1, // DarkTurquoise
        0xFF9400D3, // DarkViolet
        0xFFFF1493, // DeepPink
        0xFF00BFFF, // DeepSkyBlue
        0xFF696969, // DimGray
        0xFF1E90FF, // DodgerBlue
        0xFFB22222, // Firebrick
        0xFFFFFAF0, // FloralWhite
        0xFF228B22, // ForestGreen
        0xFFFF00FF, // Fuchsia
        0xFFDCDCDC, // Gainsboro
        0xFFF8F8FF, // GhostWhite
        0xFFFFD700, // Gold
        0xFFDAA520, // Goldenrod
        0xFF808080, // Gray
        0xFF008000, // Green
        0xFFADFF2F, // GreenYellow
        0xFFF0FFF0, // Honeydew
        0xFFFF69B4, // HotPink
        0xFFCD5C5C, // IndianRed
        0xFF4B0082, // Indigo
        0xFFFFFFF0, // Ivory
        0xFFF0E68C, // Khaki
        0xFFE6E6FA, // Lavender
        0xFFFFF0F5, // LavenderBlush
        0xFF7CFC00, // LawnGreen
        0xFFFFFACD, // LemonChiffon
        0xFFADD8E6, // LightBlue
        0xFFF08080, // LightCoral
        0xFFE0FFFF, // LightCyan
        0xFFFAFAD2, // LightGoldenrodYellow
        0xFFD3D3D3, // LightGray
        0xFF90EE90, // LightGreen
        0xFFFFB6C1, // LightPink
        0xFFFFA07A, // LightSalmon
        0xFF20B2AA, // LightSeaGreen
        0xFF87CEFA, // LightSkyBlue
        0xFF778899, // LightSlateGray
        0xFFB0C4DE, // LightSteelBlue
        0xFFFFFFE0, // LightYellow
        0xFF00FF00, // Lime
        0xFF32CD32, // LimeGreen
        0xFFFAF0E6, // Linen
        0xFFFF00FF, // Magenta
        0xFF800000, // Maroon
        0xFF66CDAA, // MediumAquamarine
        0xFF0000CD, // MediumBlue
        0xFFBA55D3, // MediumOrchid
        0xFF9370DB, // MediumPurple
        0xFF3CB371, // MediumSeaGreen
        0xFF7B68EE, // MediumSlateBlue
        0xFF00FA9A, // MediumSpringGreen
        0xFF48D1CC, // MediumTurquoise
        0xFFC71585, // MediumVioletRed
        0xFF191970, // MidnightBlue
        0xFFF5FFFA, // MintCream
        0xFFFFE4E1, // MistyRose
        0xFFFFE4B5, // Moccasin
        0xFFFFDEAD, // NavajoWhite
        0xFF000080, // Navy
        0xFFFDF5E6, // OldLace
        0xFF808000, // Olive
        0xFF6B8E23, // OliveDrab
        0xFFFFA500, // Orange
        0xFFFF4500, // OrangeRed
        0xFFDA70D6, // Orchid
        0xFFEEE8AA, // PaleGoldenrod
        0xFF98FB98, // PaleGreen
        0xFFAFEEEE, // PaleTurquoise
        0xFFDB7093, // PaleVioletRed
        0xFFFFEFD5, // PapayaWhip
        0xFFFFDAB9, // PeachPuff
        0xFFCD853F, // Peru
        0xFFFFC0CB, // Pink
        0xFFDDA0DD, // Plum
        0xFFB0E0E6, // PowderBlue
        0xFF800080, // Purple
        0xFFFF0000, // Red
        0xFFBC8F8F, // RosyBrown
        0xFF4169E1, // RoyalBlue
        0xFF8B4513, // SaddleBrown
        0xFFFA8072, // Salmon
        0xFFF4A460, // SandyBrown
        0xFF2E8B57, // SeaGreen
        0xFFFFF5EE, // SeaShell
        0xFFA0522D, // Sienna
        0xFFC0C0C0, // Silver
        0xFF87CEEB, // SkyBlue
        0xFF6A5ACD, // SlateBlue
        0xFF708090, // SlateGray
        0xFFFFFAFA, // Snow
        0xFF00FF7F, // SpringGreen
        0xFF4682B4, // SteelBlue
        0xFFD2B48C, // Tan
        0xFF008080, // Teal
        0xFFD8BFD8, // Thistle
        0xFFFF6347, // Tomato
        0xFF40E0D0, // Turquoise
        0xFFEE82EE, // Violet
        0xFFF5DEB3, // Wheat
        0xFFFFFFFF, // White
        0xFFF5F5F5, // WhiteSmoke
        0xFFFFFF00, // Yellow
        0xFF9ACD32, // YellowGreen
        0xFFF0F0F0, // ButtonFace
        0xFFFFFFFF, // ButtonHighlight
        0xFFA0A0A0, // ButtonShadow
        0xFFB9D1EA, // GradientActiveCaption
        0xFFD7E4F2, // GradientInactiveCaption
        0xFFF0F0F0, // MenuBar
        0xFF3399FF, // MenuHighlight
        0xFF663399, // RebeccaPurple
    ];
}

public readonly partial struct Color
{
    public static Color AliceBlue => new(KnownColor.AliceBlue);
    public static Color AntiqueWhite => new(KnownColor.AntiqueWhite);
    public static Color Aqua => new(KnownColor.Aqua);
    public static Color Aquamarine => new(KnownColor.Aquamarine);
    public static Color Azure => new(KnownColor.Azure);
    public static Color Beige => new(KnownColor.Beige);
    public static Color Bisque => new(KnownColor.Bisque);
    public static Color Black => new(KnownColor.Black);
    public static Color BlanchedAlmond => new(KnownColor.BlanchedAlmond);
    public static Color Blue => new(KnownColor.Blue);
    public static Color BlueViolet => new(KnownColor.BlueViolet);
    public static Color Brown => new(KnownColor.Brown);
    public static Color BurlyWood => new(KnownColor.BurlyWood);
    public static Color CadetBlue => new(KnownColor.CadetBlue);
    public static Color Chartreuse => new(KnownColor.Chartreuse);
    public static Color Chocolate => new(KnownColor.Chocolate);
    public static Color Coral => new(KnownColor.Coral);
    public static Color CornflowerBlue => new(KnownColor.CornflowerBlue);
    public static Color Cornsilk => new(KnownColor.Cornsilk);
    public static Color Crimson => new(KnownColor.Crimson);
    public static Color Cyan => new(KnownColor.Cyan);
    public static Color DarkBlue => new(KnownColor.DarkBlue);
    public static Color DarkCyan => new(KnownColor.DarkCyan);
    public static Color DarkGoldenrod => new(KnownColor.DarkGoldenrod);
    public static Color DarkGray => new(KnownColor.DarkGray);
    public static Color DarkGreen => new(KnownColor.DarkGreen);
    public static Color DarkKhaki => new(KnownColor.DarkKhaki);
    public static Color DarkMagenta => new(KnownColor.DarkMagenta);
    public static Color DarkOliveGreen => new(KnownColor.DarkOliveGreen);
    public static Color DarkOrange => new(KnownColor.DarkOrange);
    public static Color DarkOrchid => new(KnownColor.DarkOrchid);
    public static Color DarkRed => new(KnownColor.DarkRed);
    public static Color DarkSalmon => new(KnownColor.DarkSalmon);
    public static Color DarkSeaGreen => new(KnownColor.DarkSeaGreen);
    public static Color DarkSlateBlue => new(KnownColor.DarkSlateBlue);
    public static Color DarkSlateGray => new(KnownColor.DarkSlateGray);
    public static Color DarkTurquoise => new(KnownColor.DarkTurquoise);
    public static Color DarkViolet => new(KnownColor.DarkViolet);
    public static Color DeepPink => new(KnownColor.DeepPink);
    public static Color DeepSkyBlue => new(KnownColor.DeepSkyBlue);
    public static Color DimGray => new(KnownColor.DimGray);
    public static Color DodgerBlue => new(KnownColor.DodgerBlue);
    public static Color Firebrick => new(KnownColor.Firebrick);
    public static Color FloralWhite => new(KnownColor.FloralWhite);
    public static Color ForestGreen => new(KnownColor.ForestGreen);
    public static Color Fuchsia => new(KnownColor.Fuchsia);
    public static Color Gainsboro => new(KnownColor.Gainsboro);
    public static Color GhostWhite => new(KnownColor.GhostWhite);
    public static Color Gold => new(KnownColor.Gold);
    public static Color Goldenrod => new(KnownColor.Goldenrod);
    public static Color Gray => new(KnownColor.Gray);
    public static Color Green => new(KnownColor.Green);
    public static Color GreenYellow => new(KnownColor.GreenYellow);
    public static Color Honeydew => new(KnownColor.Honeydew);
    public static Color HotPink => new(KnownColor.HotPink);
    public static Color IndianRed => new(KnownColor.IndianRed);
    public static Color Indigo => new(KnownColor.Indigo);
    public static Color Ivory => new(KnownColor.Ivory);
    public static Color Khaki => new(KnownColor.Khaki);
    public static Color Lavender => new(KnownColor.Lavender);
    public static Color LavenderBlush => new(KnownColor.LavenderBlush);
    public static Color LawnGreen => new(KnownColor.LawnGreen);
    public static Color LemonChiffon => new(KnownColor.LemonChiffon);
    public static Color LightBlue => new(KnownColor.LightBlue);
    public static Color LightCoral => new(KnownColor.LightCoral);
    public static Color LightCyan => new(KnownColor.LightCyan);
    public static Color LightGoldenrodYellow => new(KnownColor.LightGoldenrodYellow);
    public static Color LightGray => new(KnownColor.LightGray);
    public static Color LightGreen => new(KnownColor.LightGreen);
    public static Color LightPink => new(KnownColor.LightPink);
    public static Color LightSalmon => new(KnownColor.LightSalmon);
    public static Color LightSeaGreen => new(KnownColor.LightSeaGreen);
    public static Color LightSkyBlue => new(KnownColor.LightSkyBlue);
    public static Color LightSlateGray => new(KnownColor.LightSlateGray);
    public static Color LightSteelBlue => new(KnownColor.LightSteelBlue);
    public static Color LightYellow => new(KnownColor.LightYellow);
    public static Color Lime => new(KnownColor.Lime);
    public static Color LimeGreen => new(KnownColor.LimeGreen);
    public static Color Linen => new(KnownColor.Linen);
    public static Color Magenta => new(KnownColor.Magenta);
    public static Color Maroon => new(KnownColor.Maroon);
    public static Color MediumAquamarine => new(KnownColor.MediumAquamarine);
    public static Color MediumBlue => new(KnownColor.MediumBlue);
    public static Color MediumOrchid => new(KnownColor.MediumOrchid);
    public static Color MediumPurple => new(KnownColor.MediumPurple);
    public static Color MediumSeaGreen => new(KnownColor.MediumSeaGreen);
    public static Color MediumSlateBlue => new(KnownColor.MediumSlateBlue);
    public static Color MediumSpringGreen => new(KnownColor.MediumSpringGreen);
    public static Color MediumTurquoise => new(KnownColor.MediumTurquoise);
    public static Color MediumVioletRed => new(KnownColor.MediumVioletRed);
    public static Color MidnightBlue => new(KnownColor.MidnightBlue);
    public static Color MintCream => new(KnownColor.MintCream);
    public static Color MistyRose => new(KnownColor.MistyRose);
    public static Color Moccasin => new(KnownColor.Moccasin);
    public static Color NavajoWhite => new(KnownColor.NavajoWhite);
    public static Color Navy => new(KnownColor.Navy);
    public static Color OldLace => new(KnownColor.OldLace);
    public static Color Olive => new(KnownColor.Olive);
    public static Color OliveDrab => new(KnownColor.OliveDrab);
    public static Color Orange => new(KnownColor.Orange);
    public static Color OrangeRed => new(KnownColor.OrangeRed);
    public static Color Orchid => new(KnownColor.Orchid);
    public static Color PaleGoldenrod => new(KnownColor.PaleGoldenrod);
    public static Color PaleGreen => new(KnownColor.PaleGreen);
    public static Color PaleTurquoise => new(KnownColor.PaleTurquoise);
    public static Color PaleVioletRed => new(KnownColor.PaleVioletRed);
    public static Color PapayaWhip => new(KnownColor.PapayaWhip);
    public static Color PeachPuff => new(KnownColor.PeachPuff);
    public static Color Peru => new(KnownColor.Peru);
    public static Color Pink => new(KnownColor.Pink);
    public static Color Plum => new(KnownColor.Plum);
    public static Color PowderBlue => new(KnownColor.PowderBlue);
    public static Color Purple => new(KnownColor.Purple);
    public static Color RebeccaPurple => new(KnownColor.RebeccaPurple);
    public static Color Red => new(KnownColor.Red);
    public static Color RosyBrown => new(KnownColor.RosyBrown);
    public static Color RoyalBlue => new(KnownColor.RoyalBlue);
    public static Color SaddleBrown => new(KnownColor.SaddleBrown);
    public static Color Salmon => new(KnownColor.Salmon);
    public static Color SandyBrown => new(KnownColor.SandyBrown);
    public static Color SeaGreen => new(KnownColor.SeaGreen);
    public static Color SeaShell => new(KnownColor.SeaShell);
    public static Color Sienna => new(KnownColor.Sienna);
    public static Color Silver => new(KnownColor.Silver);
    public static Color SkyBlue => new(KnownColor.SkyBlue);
    public static Color SlateBlue => new(KnownColor.SlateBlue);
    public static Color SlateGray => new(KnownColor.SlateGray);
    public static Color Snow => new(KnownColor.Snow);
    public static Color SpringGreen => new(KnownColor.SpringGreen);
    public static Color SteelBlue => new(KnownColor.SteelBlue);
    public static Color Tan => new(KnownColor.Tan);
    public static Color Teal => new(KnownColor.Teal);
    public static Color Thistle => new(KnownColor.Thistle);
    public static Color Tomato => new(KnownColor.Tomato);
    public static Color Transparent => new(KnownColor.Transparent);
    public static Color Turquoise => new(KnownColor.Turquoise);
    public static Color Violet => new(KnownColor.Violet);
    public static Color Wheat => new(KnownColor.Wheat);
    public static Color White => new(KnownColor.White);
    public static Color WhiteSmoke => new(KnownColor.WhiteSmoke);
    public static Color Yellow => new(KnownColor.Yellow);
    public static Color YellowGreen => new(KnownColor.YellowGreen);
}
