// <auto-generated>Generated from the named colors of System.Drawing.Color.</auto-generated>
#nullable enable

namespace System.Drawing;

/// <summary>Immutable solid brushes for all named colors.</summary>
public static class Brushes
{
    private static readonly Brush?[] cache = new Brush?[Enum.GetValues<KnownColor>().Max(c => (int)c) + 1];

    public static Brush AliceBlue => Get(KnownColor.AliceBlue);

    public static Brush AntiqueWhite => Get(KnownColor.AntiqueWhite);

    public static Brush Aqua => Get(KnownColor.Aqua);

    public static Brush Aquamarine => Get(KnownColor.Aquamarine);

    public static Brush Azure => Get(KnownColor.Azure);

    public static Brush Beige => Get(KnownColor.Beige);

    public static Brush Bisque => Get(KnownColor.Bisque);

    public static Brush Black => Get(KnownColor.Black);

    public static Brush BlanchedAlmond => Get(KnownColor.BlanchedAlmond);

    public static Brush Blue => Get(KnownColor.Blue);

    public static Brush BlueViolet => Get(KnownColor.BlueViolet);

    public static Brush Brown => Get(KnownColor.Brown);

    public static Brush BurlyWood => Get(KnownColor.BurlyWood);

    public static Brush CadetBlue => Get(KnownColor.CadetBlue);

    public static Brush Chartreuse => Get(KnownColor.Chartreuse);

    public static Brush Chocolate => Get(KnownColor.Chocolate);

    public static Brush Coral => Get(KnownColor.Coral);

    public static Brush CornflowerBlue => Get(KnownColor.CornflowerBlue);

    public static Brush Cornsilk => Get(KnownColor.Cornsilk);

    public static Brush Crimson => Get(KnownColor.Crimson);

    public static Brush Cyan => Get(KnownColor.Cyan);

    public static Brush DarkBlue => Get(KnownColor.DarkBlue);

    public static Brush DarkCyan => Get(KnownColor.DarkCyan);

    public static Brush DarkGoldenrod => Get(KnownColor.DarkGoldenrod);

    public static Brush DarkGray => Get(KnownColor.DarkGray);

    public static Brush DarkGreen => Get(KnownColor.DarkGreen);

    public static Brush DarkKhaki => Get(KnownColor.DarkKhaki);

    public static Brush DarkMagenta => Get(KnownColor.DarkMagenta);

    public static Brush DarkOliveGreen => Get(KnownColor.DarkOliveGreen);

    public static Brush DarkOrange => Get(KnownColor.DarkOrange);

    public static Brush DarkOrchid => Get(KnownColor.DarkOrchid);

    public static Brush DarkRed => Get(KnownColor.DarkRed);

    public static Brush DarkSalmon => Get(KnownColor.DarkSalmon);

    public static Brush DarkSeaGreen => Get(KnownColor.DarkSeaGreen);

    public static Brush DarkSlateBlue => Get(KnownColor.DarkSlateBlue);

    public static Brush DarkSlateGray => Get(KnownColor.DarkSlateGray);

    public static Brush DarkTurquoise => Get(KnownColor.DarkTurquoise);

    public static Brush DarkViolet => Get(KnownColor.DarkViolet);

    public static Brush DeepPink => Get(KnownColor.DeepPink);

    public static Brush DeepSkyBlue => Get(KnownColor.DeepSkyBlue);

    public static Brush DimGray => Get(KnownColor.DimGray);

    public static Brush DodgerBlue => Get(KnownColor.DodgerBlue);

    public static Brush Firebrick => Get(KnownColor.Firebrick);

    public static Brush FloralWhite => Get(KnownColor.FloralWhite);

    public static Brush ForestGreen => Get(KnownColor.ForestGreen);

    public static Brush Fuchsia => Get(KnownColor.Fuchsia);

    public static Brush Gainsboro => Get(KnownColor.Gainsboro);

    public static Brush GhostWhite => Get(KnownColor.GhostWhite);

    public static Brush Gold => Get(KnownColor.Gold);

    public static Brush Goldenrod => Get(KnownColor.Goldenrod);

    public static Brush Gray => Get(KnownColor.Gray);

    public static Brush Green => Get(KnownColor.Green);

    public static Brush GreenYellow => Get(KnownColor.GreenYellow);

    public static Brush Honeydew => Get(KnownColor.Honeydew);

    public static Brush HotPink => Get(KnownColor.HotPink);

    public static Brush IndianRed => Get(KnownColor.IndianRed);

    public static Brush Indigo => Get(KnownColor.Indigo);

    public static Brush Ivory => Get(KnownColor.Ivory);

    public static Brush Khaki => Get(KnownColor.Khaki);

    public static Brush Lavender => Get(KnownColor.Lavender);

    public static Brush LavenderBlush => Get(KnownColor.LavenderBlush);

    public static Brush LawnGreen => Get(KnownColor.LawnGreen);

    public static Brush LemonChiffon => Get(KnownColor.LemonChiffon);

    public static Brush LightBlue => Get(KnownColor.LightBlue);

    public static Brush LightCoral => Get(KnownColor.LightCoral);

    public static Brush LightCyan => Get(KnownColor.LightCyan);

    public static Brush LightGoldenrodYellow => Get(KnownColor.LightGoldenrodYellow);

    public static Brush LightGray => Get(KnownColor.LightGray);

    public static Brush LightGreen => Get(KnownColor.LightGreen);

    public static Brush LightPink => Get(KnownColor.LightPink);

    public static Brush LightSalmon => Get(KnownColor.LightSalmon);

    public static Brush LightSeaGreen => Get(KnownColor.LightSeaGreen);

    public static Brush LightSkyBlue => Get(KnownColor.LightSkyBlue);

    public static Brush LightSlateGray => Get(KnownColor.LightSlateGray);

    public static Brush LightSteelBlue => Get(KnownColor.LightSteelBlue);

    public static Brush LightYellow => Get(KnownColor.LightYellow);

    public static Brush Lime => Get(KnownColor.Lime);

    public static Brush LimeGreen => Get(KnownColor.LimeGreen);

    public static Brush Linen => Get(KnownColor.Linen);

    public static Brush Magenta => Get(KnownColor.Magenta);

    public static Brush Maroon => Get(KnownColor.Maroon);

    public static Brush MediumAquamarine => Get(KnownColor.MediumAquamarine);

    public static Brush MediumBlue => Get(KnownColor.MediumBlue);

    public static Brush MediumOrchid => Get(KnownColor.MediumOrchid);

    public static Brush MediumPurple => Get(KnownColor.MediumPurple);

    public static Brush MediumSeaGreen => Get(KnownColor.MediumSeaGreen);

    public static Brush MediumSlateBlue => Get(KnownColor.MediumSlateBlue);

    public static Brush MediumSpringGreen => Get(KnownColor.MediumSpringGreen);

    public static Brush MediumTurquoise => Get(KnownColor.MediumTurquoise);

    public static Brush MediumVioletRed => Get(KnownColor.MediumVioletRed);

    public static Brush MidnightBlue => Get(KnownColor.MidnightBlue);

    public static Brush MintCream => Get(KnownColor.MintCream);

    public static Brush MistyRose => Get(KnownColor.MistyRose);

    public static Brush Moccasin => Get(KnownColor.Moccasin);

    public static Brush NavajoWhite => Get(KnownColor.NavajoWhite);

    public static Brush Navy => Get(KnownColor.Navy);

    public static Brush OldLace => Get(KnownColor.OldLace);

    public static Brush Olive => Get(KnownColor.Olive);

    public static Brush OliveDrab => Get(KnownColor.OliveDrab);

    public static Brush Orange => Get(KnownColor.Orange);

    public static Brush OrangeRed => Get(KnownColor.OrangeRed);

    public static Brush Orchid => Get(KnownColor.Orchid);

    public static Brush PaleGoldenrod => Get(KnownColor.PaleGoldenrod);

    public static Brush PaleGreen => Get(KnownColor.PaleGreen);

    public static Brush PaleTurquoise => Get(KnownColor.PaleTurquoise);

    public static Brush PaleVioletRed => Get(KnownColor.PaleVioletRed);

    public static Brush PapayaWhip => Get(KnownColor.PapayaWhip);

    public static Brush PeachPuff => Get(KnownColor.PeachPuff);

    public static Brush Peru => Get(KnownColor.Peru);

    public static Brush Pink => Get(KnownColor.Pink);

    public static Brush Plum => Get(KnownColor.Plum);

    public static Brush PowderBlue => Get(KnownColor.PowderBlue);

    public static Brush Purple => Get(KnownColor.Purple);

    public static Brush RebeccaPurple => Get(KnownColor.RebeccaPurple);

    public static Brush Red => Get(KnownColor.Red);

    public static Brush RosyBrown => Get(KnownColor.RosyBrown);

    public static Brush RoyalBlue => Get(KnownColor.RoyalBlue);

    public static Brush SaddleBrown => Get(KnownColor.SaddleBrown);

    public static Brush Salmon => Get(KnownColor.Salmon);

    public static Brush SandyBrown => Get(KnownColor.SandyBrown);

    public static Brush SeaGreen => Get(KnownColor.SeaGreen);

    public static Brush SeaShell => Get(KnownColor.SeaShell);

    public static Brush Sienna => Get(KnownColor.Sienna);

    public static Brush Silver => Get(KnownColor.Silver);

    public static Brush SkyBlue => Get(KnownColor.SkyBlue);

    public static Brush SlateBlue => Get(KnownColor.SlateBlue);

    public static Brush SlateGray => Get(KnownColor.SlateGray);

    public static Brush Snow => Get(KnownColor.Snow);

    public static Brush SpringGreen => Get(KnownColor.SpringGreen);

    public static Brush SteelBlue => Get(KnownColor.SteelBlue);

    public static Brush Tan => Get(KnownColor.Tan);

    public static Brush Teal => Get(KnownColor.Teal);

    public static Brush Thistle => Get(KnownColor.Thistle);

    public static Brush Tomato => Get(KnownColor.Tomato);

    public static Brush Transparent => Get(KnownColor.Transparent);

    public static Brush Turquoise => Get(KnownColor.Turquoise);

    public static Brush Violet => Get(KnownColor.Violet);

    public static Brush Wheat => Get(KnownColor.Wheat);

    public static Brush White => Get(KnownColor.White);

    public static Brush WhiteSmoke => Get(KnownColor.WhiteSmoke);

    public static Brush Yellow => Get(KnownColor.Yellow);

    public static Brush YellowGreen => Get(KnownColor.YellowGreen);

    private static Brush Get(KnownColor color) => cache[(int)color] ??= new SolidBrush(Color.FromKnownColor(color), immutable: true);
}
