// <auto-generated>Generated from the named colors of System.Drawing.Color.</auto-generated>
#nullable enable

namespace System.Drawing;

/// <summary>Immutable one-unit-wide pens for all named colors.</summary>
public static class Pens
{
    private static readonly Pen?[] cache = new Pen?[Enum.GetValues<KnownColor>().Max(c => (int)c) + 1];

    public static Pen AliceBlue => Get(KnownColor.AliceBlue);

    public static Pen AntiqueWhite => Get(KnownColor.AntiqueWhite);

    public static Pen Aqua => Get(KnownColor.Aqua);

    public static Pen Aquamarine => Get(KnownColor.Aquamarine);

    public static Pen Azure => Get(KnownColor.Azure);

    public static Pen Beige => Get(KnownColor.Beige);

    public static Pen Bisque => Get(KnownColor.Bisque);

    public static Pen Black => Get(KnownColor.Black);

    public static Pen BlanchedAlmond => Get(KnownColor.BlanchedAlmond);

    public static Pen Blue => Get(KnownColor.Blue);

    public static Pen BlueViolet => Get(KnownColor.BlueViolet);

    public static Pen Brown => Get(KnownColor.Brown);

    public static Pen BurlyWood => Get(KnownColor.BurlyWood);

    public static Pen CadetBlue => Get(KnownColor.CadetBlue);

    public static Pen Chartreuse => Get(KnownColor.Chartreuse);

    public static Pen Chocolate => Get(KnownColor.Chocolate);

    public static Pen Coral => Get(KnownColor.Coral);

    public static Pen CornflowerBlue => Get(KnownColor.CornflowerBlue);

    public static Pen Cornsilk => Get(KnownColor.Cornsilk);

    public static Pen Crimson => Get(KnownColor.Crimson);

    public static Pen Cyan => Get(KnownColor.Cyan);

    public static Pen DarkBlue => Get(KnownColor.DarkBlue);

    public static Pen DarkCyan => Get(KnownColor.DarkCyan);

    public static Pen DarkGoldenrod => Get(KnownColor.DarkGoldenrod);

    public static Pen DarkGray => Get(KnownColor.DarkGray);

    public static Pen DarkGreen => Get(KnownColor.DarkGreen);

    public static Pen DarkKhaki => Get(KnownColor.DarkKhaki);

    public static Pen DarkMagenta => Get(KnownColor.DarkMagenta);

    public static Pen DarkOliveGreen => Get(KnownColor.DarkOliveGreen);

    public static Pen DarkOrange => Get(KnownColor.DarkOrange);

    public static Pen DarkOrchid => Get(KnownColor.DarkOrchid);

    public static Pen DarkRed => Get(KnownColor.DarkRed);

    public static Pen DarkSalmon => Get(KnownColor.DarkSalmon);

    public static Pen DarkSeaGreen => Get(KnownColor.DarkSeaGreen);

    public static Pen DarkSlateBlue => Get(KnownColor.DarkSlateBlue);

    public static Pen DarkSlateGray => Get(KnownColor.DarkSlateGray);

    public static Pen DarkTurquoise => Get(KnownColor.DarkTurquoise);

    public static Pen DarkViolet => Get(KnownColor.DarkViolet);

    public static Pen DeepPink => Get(KnownColor.DeepPink);

    public static Pen DeepSkyBlue => Get(KnownColor.DeepSkyBlue);

    public static Pen DimGray => Get(KnownColor.DimGray);

    public static Pen DodgerBlue => Get(KnownColor.DodgerBlue);

    public static Pen Firebrick => Get(KnownColor.Firebrick);

    public static Pen FloralWhite => Get(KnownColor.FloralWhite);

    public static Pen ForestGreen => Get(KnownColor.ForestGreen);

    public static Pen Fuchsia => Get(KnownColor.Fuchsia);

    public static Pen Gainsboro => Get(KnownColor.Gainsboro);

    public static Pen GhostWhite => Get(KnownColor.GhostWhite);

    public static Pen Gold => Get(KnownColor.Gold);

    public static Pen Goldenrod => Get(KnownColor.Goldenrod);

    public static Pen Gray => Get(KnownColor.Gray);

    public static Pen Green => Get(KnownColor.Green);

    public static Pen GreenYellow => Get(KnownColor.GreenYellow);

    public static Pen Honeydew => Get(KnownColor.Honeydew);

    public static Pen HotPink => Get(KnownColor.HotPink);

    public static Pen IndianRed => Get(KnownColor.IndianRed);

    public static Pen Indigo => Get(KnownColor.Indigo);

    public static Pen Ivory => Get(KnownColor.Ivory);

    public static Pen Khaki => Get(KnownColor.Khaki);

    public static Pen Lavender => Get(KnownColor.Lavender);

    public static Pen LavenderBlush => Get(KnownColor.LavenderBlush);

    public static Pen LawnGreen => Get(KnownColor.LawnGreen);

    public static Pen LemonChiffon => Get(KnownColor.LemonChiffon);

    public static Pen LightBlue => Get(KnownColor.LightBlue);

    public static Pen LightCoral => Get(KnownColor.LightCoral);

    public static Pen LightCyan => Get(KnownColor.LightCyan);

    public static Pen LightGoldenrodYellow => Get(KnownColor.LightGoldenrodYellow);

    public static Pen LightGray => Get(KnownColor.LightGray);

    public static Pen LightGreen => Get(KnownColor.LightGreen);

    public static Pen LightPink => Get(KnownColor.LightPink);

    public static Pen LightSalmon => Get(KnownColor.LightSalmon);

    public static Pen LightSeaGreen => Get(KnownColor.LightSeaGreen);

    public static Pen LightSkyBlue => Get(KnownColor.LightSkyBlue);

    public static Pen LightSlateGray => Get(KnownColor.LightSlateGray);

    public static Pen LightSteelBlue => Get(KnownColor.LightSteelBlue);

    public static Pen LightYellow => Get(KnownColor.LightYellow);

    public static Pen Lime => Get(KnownColor.Lime);

    public static Pen LimeGreen => Get(KnownColor.LimeGreen);

    public static Pen Linen => Get(KnownColor.Linen);

    public static Pen Magenta => Get(KnownColor.Magenta);

    public static Pen Maroon => Get(KnownColor.Maroon);

    public static Pen MediumAquamarine => Get(KnownColor.MediumAquamarine);

    public static Pen MediumBlue => Get(KnownColor.MediumBlue);

    public static Pen MediumOrchid => Get(KnownColor.MediumOrchid);

    public static Pen MediumPurple => Get(KnownColor.MediumPurple);

    public static Pen MediumSeaGreen => Get(KnownColor.MediumSeaGreen);

    public static Pen MediumSlateBlue => Get(KnownColor.MediumSlateBlue);

    public static Pen MediumSpringGreen => Get(KnownColor.MediumSpringGreen);

    public static Pen MediumTurquoise => Get(KnownColor.MediumTurquoise);

    public static Pen MediumVioletRed => Get(KnownColor.MediumVioletRed);

    public static Pen MidnightBlue => Get(KnownColor.MidnightBlue);

    public static Pen MintCream => Get(KnownColor.MintCream);

    public static Pen MistyRose => Get(KnownColor.MistyRose);

    public static Pen Moccasin => Get(KnownColor.Moccasin);

    public static Pen NavajoWhite => Get(KnownColor.NavajoWhite);

    public static Pen Navy => Get(KnownColor.Navy);

    public static Pen OldLace => Get(KnownColor.OldLace);

    public static Pen Olive => Get(KnownColor.Olive);

    public static Pen OliveDrab => Get(KnownColor.OliveDrab);

    public static Pen Orange => Get(KnownColor.Orange);

    public static Pen OrangeRed => Get(KnownColor.OrangeRed);

    public static Pen Orchid => Get(KnownColor.Orchid);

    public static Pen PaleGoldenrod => Get(KnownColor.PaleGoldenrod);

    public static Pen PaleGreen => Get(KnownColor.PaleGreen);

    public static Pen PaleTurquoise => Get(KnownColor.PaleTurquoise);

    public static Pen PaleVioletRed => Get(KnownColor.PaleVioletRed);

    public static Pen PapayaWhip => Get(KnownColor.PapayaWhip);

    public static Pen PeachPuff => Get(KnownColor.PeachPuff);

    public static Pen Peru => Get(KnownColor.Peru);

    public static Pen Pink => Get(KnownColor.Pink);

    public static Pen Plum => Get(KnownColor.Plum);

    public static Pen PowderBlue => Get(KnownColor.PowderBlue);

    public static Pen Purple => Get(KnownColor.Purple);

    public static Pen RebeccaPurple => Get(KnownColor.RebeccaPurple);

    public static Pen Red => Get(KnownColor.Red);

    public static Pen RosyBrown => Get(KnownColor.RosyBrown);

    public static Pen RoyalBlue => Get(KnownColor.RoyalBlue);

    public static Pen SaddleBrown => Get(KnownColor.SaddleBrown);

    public static Pen Salmon => Get(KnownColor.Salmon);

    public static Pen SandyBrown => Get(KnownColor.SandyBrown);

    public static Pen SeaGreen => Get(KnownColor.SeaGreen);

    public static Pen SeaShell => Get(KnownColor.SeaShell);

    public static Pen Sienna => Get(KnownColor.Sienna);

    public static Pen Silver => Get(KnownColor.Silver);

    public static Pen SkyBlue => Get(KnownColor.SkyBlue);

    public static Pen SlateBlue => Get(KnownColor.SlateBlue);

    public static Pen SlateGray => Get(KnownColor.SlateGray);

    public static Pen Snow => Get(KnownColor.Snow);

    public static Pen SpringGreen => Get(KnownColor.SpringGreen);

    public static Pen SteelBlue => Get(KnownColor.SteelBlue);

    public static Pen Tan => Get(KnownColor.Tan);

    public static Pen Teal => Get(KnownColor.Teal);

    public static Pen Thistle => Get(KnownColor.Thistle);

    public static Pen Tomato => Get(KnownColor.Tomato);

    public static Pen Transparent => Get(KnownColor.Transparent);

    public static Pen Turquoise => Get(KnownColor.Turquoise);

    public static Pen Violet => Get(KnownColor.Violet);

    public static Pen Wheat => Get(KnownColor.Wheat);

    public static Pen White => Get(KnownColor.White);

    public static Pen WhiteSmoke => Get(KnownColor.WhiteSmoke);

    public static Pen Yellow => Get(KnownColor.Yellow);

    public static Pen YellowGreen => Get(KnownColor.YellowGreen);

    private static Pen Get(KnownColor color) => cache[(int)color] ??= new Pen(Color.FromKnownColor(color), immutable: true);
}
